baseURL: https://edpark.art
title: Ed Park - Art
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: '' # todo: set your analytics id.

params:
  image: /images/banner.png
  subtitle: 
  copyright: All rights reserved. # todo: set your copyright type.
  author: Ed Park # todo: set your full name.
  dontShowSource: true
  portfolio:
    columns:
      desktop:
        default: 3
      mobile:
        default: 2
  socials:
    # todo: add your social accounts.
    - icon: 'fab fa-instagram fa-lg'
      url: 'https://instagram.com/edwardpark'
      landing: true
  # homepage: "/work" # todo: uncomment homepage, homepage link is mostly same with menu.main[0]
  specialPages:
    - work
    - archive
  bypassWelcomePage: false # redirects "/" to "homepage" when it's true.
  plausible: '' # todo: set your plausible id.
  disableRadius: false
  moveIt: false # Moves Title and Meta info down, only visible when scroll.
  DisableAlwaysResize: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

# todo: uncomment menu.main array after you create contents.
# menu:
#   main:
#     - name: work
#       url: /work/
#       weight: 1
